sudo: required
dist: trusty
language: c
compiler: gcc

install: ./install-dependencies.sh

script:
- which python2
- export PYTHON=/opt/pyenv/shims/python2
- ./test.sh
- cp .config lede/
- cd $TRAVIS_BUILD_DIR/lede
- git checkout lede-17.01
- ./scripts/feeds update
- ./scripts/feeds install -a
- make -j3 tools/tar/compile
- make -j3 download
- rm tools/pkg-config/Makefile
- cp ../pkg-config/Makefile tools/pkg-config/
- rm tools/bison/Makefile
- cp ../bison/Makefile tools/bison/
- rm tools/findutils/Makefile
- cp ../findutils/Makefile tools/findutils/
- make -j1 V=s tools/findutils/install
- make -j1 tools/install 
