sudo: required
dist: trusty
language: c
compiler: gcc

install: ./install-dependencies.sh

script:
- cp .config lede/
- cd $TRAVIS_BUILD_DIR/lede
- git checkout lede-17.01
- ./scripts/feeds update
- ./scripts/feeds install -a
- make -j3 tools/tar/compile V=s
- make -j3 download V=s
- ls -l dl
- make -j1 missing-macros
- make tools/install V=sc j=1
