sudo: enabled
language: c
compiler: gcc

install: ./install-dependencies.sh

script:
- cp .config lede/
- cd $TRAVIS_BUILD_DIR/lede
- ./scripts/feeds update
- ./scripts/feeds install -a
- make -j3 tools/tar/compile V=s
- make -j3 download V=s
